### PR TITLE
Vrt-bot log in file

### PR DESCRIPTION
**Pull request by f-necas**
This PR adds logs to stdout and to vrtlog file.

It allows end-user to have an access to last vrt bot logs.

### CODE REVIEW

**Review by pmauduit — APPROVED** [review]
lgtm

**Comment by edevosc2c** [comment]
I see two issues here:

- There is no "logrotate" so your file will quickly grow up to a point of getting to a hundred GBs if you do not do anything after half a year.
   In Kubernetes there is a log rotation for pods logs, so no issues for the console logs.
   But for the file "vrtbot.log", you should do some kind of automatic log cleanup.
- Also, if you think on the user side, having everything in a single log file makes it difficult to distinguish the errors from one vrt to another.
  It's not a critical issue but could help for the user experience.

**Comment by pmauduit** [comment]
> * There is no "logrotate" so your file will quickly grow up to a point of getting to a hundred GBs if you do not do anything after half a year.

the file is removed / recreated at each run

**Comment by edevosc2c** [comment]
> > * There is no "logrotate" so your file will quickly grow up to a point of getting to a hundred GBs if you do not do anything after half a year.
> 
> the file is removed / recreated at each run

Right I haven't seen the "rm" command above.

---------

Anyway after discussion with @f-necas.

The second point remains present, I proposed to keep the 10th last logs files. Because the user may want to see the previous logs of the vrt-bot import process.

**Pull request merged**
